# VCD Waveform Viewer

A Python/Tkinter application for viewing and analyzing Value Change Dump (VCD) waveform files generated by digital circuit simulators.

![VCD Waveform Viewer](https://img.shields.io/badge/Python-3.8+-blue.svg)
![License](https://img.shields.io/badge/license-MIT-green.svg)

## Features

### Core Functionality
- **VCD File Parsing** - Full support for standard VCD format
- **Digital Signal Display** - High/low waveforms for single-bit signals
- **Bus Signal Display** - Multi-bit signals with hex value labels
- **Hierarchical Signal Names** - Supports scoped signal paths

### Visualization
- **Custom Signal Colors** - Right-click to change individual signal colors
- **Time Grid** - Automatic time axis with intelligent tick marks
- **Zoom Controls** - Zoom in/out/fit with toolbar or keyboard shortcuts
- **Pan Navigation** - Click and drag to pan the waveform view
- **Signal Reordering** - Drag signals in the list to reorder display

### Timing Analysis
- **Interactive Cursor** - Draggable time cursor with precise measurements
- **Time Markers** - Double-click to place markers, drag to reposition
- **Edge Snapping** - Markers and cursor snap to signal transitions
- **Time Deltas** - Display time differences between cursor and markers
- **Snap Override** - Hold Alt to disable snapping while dragging

### User Interface
- **Signal Search** - Real-time filtering of signal names
- **Multi-Select** - Select/deselect multiple signals simultaneously
- **Time Base Conversion** - View times in fs, ps, ns, us, ms, or s
- **Adaptive Precision** - Zoom-aware time label precision
- **Status Bar** - Real-time feedback for all operations

## Installation

### Requirements
- Python 3.8 or higher
- Tkinter (usually included with Python)

### Setup
1. Clone or download this repository
2. Ensure all files are in the same directory:
   ```
   vcd_viewer/
   ├── main.py
   ├── models.py
   ├── parser.py
   ├── canvas.py
   └── viewer.py
   ```

3. Run the application:
   ```bash
   python main.py
   ```

## Usage

### Loading a VCD File
1. Click **"Open VCD"** or press `Ctrl+O`
2. Select your `.vcd` file
3. All signals will be loaded and selected by default

### Navigating Waveforms
- **Zoom In**: Click toolbar button or press `Ctrl++`
- **Zoom Out**: Click toolbar button or press `Ctrl+-`
- **Zoom Fit**: Click toolbar button or press `Ctrl+0`
- **Pan**: Click and drag anywhere on the waveform canvas
- **Scroll**: Use scrollbars or mouse wheel

### Working with Signals
- **Select/Deselect**: Click signal names in the list
- **Select All**: Click "Select All" button
- **Clear All**: Click "Clear All" button
- **Search**: Type in the search box to filter signals
- **Reorder**: Click and drag signal names to reorder display
- **Change Color**: Right-click signal name → Change Color → pick a color
- **Hide Signal**: Right-click signal name → Hide Signal

### Timing Measurements
- **Show Cursor**: Click "Toggle Cursor" or press `C`
- **Move Cursor**: Click and drag the yellow dashed line
- **Place Marker**: Double-click on the waveform
- **Move Marker**: Click and drag cyan marker lines
- **Select Marker**: Click marker to select (turns brighter)
- **View Delta**: Delta between cursor and selected marker shown in status bar
- **Delete Markers**: Click "Delete Selected" or press `Delete`
- **Clear All Markers**: Click "Clear Markers"
- **Disable Snap**: Hold `Alt` while dragging cursor/markers

### Keyboard Shortcuts

| Key Combination | Action |
|-----------------|--------|
| `Ctrl+O`        | Open VCD file |
| `Ctrl++`        | Zoom in |
| `Ctrl+-`        | Zoom out |
| `Ctrl+0`        | Zoom fit |
| `F5`            | Refresh display |
| `C`             | Toggle cursor visibility |
| `Delete`        | Clear all markers |

### Time Base Conversion
Select a time base from the dropdown:
- **auto** - Automatically choose appropriate units
- **fs** - Display all times in femtoseconds
- **ps** - Display all times in picoseconds
- **ns** - Display all times in nanoseconds
- **us** - Display all times in microseconds
- **ms** - Display all times in milliseconds
- **s** - Display all times in seconds

## VCD File Format

The viewer supports standard VCD format with:
- `$timescale` directive for time units
- `$scope` and `$upscope` for hierarchical signals
- `$var` declarations for signal definitions
- Timestamp markers with `#<time>`
- Binary values: `0`, `1`, `x`, `z`
- Bus values: `b<binary> <id>`
- Real values: `r<real> <id>`

### Example VCD File
```vcd
$timescale 1ns $end
$scope module top $end
$var wire 1 ! clk $end
$var wire 8 " data $end
$upscope $end
$enddefinitions $end
#0
0!
b00000000 "
#10
1!
b11110000 "
#20
0!
```

## Project Structure

```
vcd_viewer/
├── main.py       # Application entry point
├── models.py     # Data models (Signal, Marker, Cursor, WaveformData)
├── parser.py     # VCD file parser
├── canvas.py     # Waveform rendering canvas
└── viewer.py     # Main window and UI controls
```

## Troubleshooting

### Signals Not Displaying
- Check that signals are selected in the signal list
- Verify the VCD file is valid
- Try "Zoom Fit" to see the entire timeline

### Drag and Drop Issues
- Ensure you're clicking and dragging (not just clicking)
- Move the mouse at least 5 pixels for drag to activate
- Try dragging from the middle of the signal name

### Context Menu Issues
- Make sure you're right-clicking on a signal name
- On Mac, try `Ctrl+Click` if right-click doesn't work

### Time Label Precision
- Use the Time Base dropdown to manually set units
- Zoom in for more precision, zoom out for less

## Contributing

Feel free to submit issues and enhancement requests.

## License

MIT License - feel free to use and modify for your projects.

## Credits

Created as a tool for digital design verification and debugging.

---

**Version**: 1.0  
**Author**: VCD Viewer Team  
**Last Updated**: 2025